from backend.app.main import app


def test_phase_9_frontend_endpoint_contracts_are_registered() -> None:
    paths = {route.path for route in app.routes}
    expected_paths = {
        "/health",
        "/health/system",
        "/ingestion/status",
        "/ingestion/sources",
        "/ingestion/documents",
        "/ingestion/summary",
        "/ingestion/sec/company",
        "/ingestion/rss",
        "/ingestion/local-file",
        "/ingestion/macro/local-csv",
        "/processing/status",
        "/processing/documents",
        "/processing/run",
        "/processing/document/{document_id}",
        "/processing/chunks/{processed_document_id}",
        "/processing/summary",
        "/retrieval/status",
        "/retrieval/index/build",
        "/retrieval/search",
        "/retrieval/index",
        "/retrieval/summary",
        "/retrieval/benchmark",
        "/rag/status",
        "/rag/ask",
        "/rag/evidence-only",
        "/rag/history",
        "/rag/history/{response_id}",
        "/reasoning/status",
        "/reasoning/analyze-scenario",
        "/reasoning/causal-chain",
        "/reasoning/evidence-map",
        "/reasoning/history",
        "/reasoning/history/{reasoning_id}",
        "/risk/status",
        "/risk/score-scenario",
        "/risk/history",
        "/risk/history/{risk_id}",
        "/explainability/status",
        "/explainability/explain-latest",
        "/explainability/explain-risk/{risk_id}",
        "/explainability/explain-reasoning/{reasoning_id}",
        "/explainability/explain-rag/{response_id}",
        "/explainability/history",
        "/explainability/history/{explainability_id}",
        "/agents/status",
        "/agents/available",
        "/agents/run-workflow",
        "/agents/run-single",
        "/agents/history",
        "/agents/history/{agent_run_id}",
        "/performance/status",
        "/performance/resources",
        "/performance/cache/stats",
        "/performance/cache/clear",
        "/performance/benchmark/run",
        "/performance/benchmark/history",
        "/performance/benchmark/history/{benchmark_id}",
        "/deployment/status",
        "/deployment/readiness-check",
        "/deployment/api-audit",
        "/deployment/security-review",
        "/deployment/governance-plan",
        "/deployment/observability-plan",
        "/deployment/runbook",
        "/deployment/final-report",
        "/deployment/reports",
        "/deployment/reports/{report_id}",
    }

    assert expected_paths.issubset(paths)
